#pragma once

enum OBJ_STATE{ PLAY, DESTROY, WAIT };

enum OBJID 
{
	OBJ_ENEMY, PLAYER_ATT, 
	ENEMY_ATT, OBJ_UI, OBJ_GROUND, OBJ_EFFECT, 
	OBJ_INTERECTION, OBJ_PLAYER, OBJ_END
};

enum SCENEID 
{ 
	SCENE_LOGO, SCENE_TITLE, SCENE_STAGE1, 
	SCENE_MIDBOSS, SCENE_BOSS, 
	SCENE_END
};

enum ENEMYTYPE
{
	EMPTY, NORMAL, SWORD, SPARK, TYPE_BOSS, ENEMYTYPE_END
};